### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by fabianmendes**
CC-BY-NC-SA-4.0

### CODE REVIEW

**Comment by fabianmendes** [comment]
I really consider that this License is such better than the CC-BY-NC because at here (-SA) makes the next authors use the same lincense. This is important, as I mentioned into the Issue: **Licensing https://github.com/MtMNC/Bionicle-Fonts/issues/1#issuecomment-421421490**.

**Comment by MtMNC** [comment]
@fidian @danny316p Thoughts?

**Comment by fidian** [comment]
I'm happy with any license. :-) At least it tries to ensure that the works are not used for commercial uses, which should help keep this work out of legal hot water. (Standard "I am not a lawyer" disclaimer here, but it does seem that companies pursue others that financially gain far more than they pursue a creative commons work.)

**Comment by danny316p** [comment]
That license sounds like a good fit to me.

**Pull request merged**
